# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95bc79139ba90d9e16e0b23706a0a88b4fc2daf6cca74b72f66b80bf4b6948b6112546ce3da59e0d6ab61af2c06728988c0f71d74d83fe94499cadf20d5e09c0

test:
  secret_key_base: 16d381058164e1ad01100a95195582d24cc8da0874349a5fa0a101bcc78335dd6fa6bd478520d39be879f8a714dd7a2721a36b3f3ad06e35ff532fc2cb1dffee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
